# Generated by Django 5.2.7 on 2025-11-13 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_meeting_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="important_participants",
            field=models.ManyToManyField(
                blank=True,
                help_text="重要参会人",
                related_name="important_meetings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[("scheduled", "已安排"), ("cancelled", "已取消")],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
